[package]
name = "ray-trace-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.3.1", features=["wasm_js"] }
image = "0.25.5"
rand = "0.9.0"
wasm-bindgen = "0.2"

